"""init

Revision ID: d0cc55f309cd
Revises: 
Create Date: 2026-04-12 19:56:07.670777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0cc55f309cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bank', sa.String(length=200), nullable=True),
    sa.Column('account_no', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('open_id', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('leave_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_no'), 'employees', ['employee_no'], unique=True)
    op.create_index(op.f('ix_employees_open_id'), 'employees', ['open_id'], unique=True)
    op.create_foreign_key(None, 'departments', 'employees', ['manager_id'], ['id'])
    op.create_table('expense_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_code'), 'expense_categories', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tax_no', sa.String(length=50), nullable=True),
    sa.Column('bank', sa.String(length=200), nullable=True),
    sa.Column('account_no', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_table('brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_code'), 'brands', ['code'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_address', sa.Text(), nullable=True),
    sa.Column('settlement_mode', sa.String(length=20), nullable=False),
    sa.Column('credit_days', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('salesman_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['salesman_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expense_no', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_account_id', sa.String(length=36), nullable=True),
    sa.Column('reimbursement_account_id', sa.String(length=36), nullable=True),
    sa.Column('reimbursement_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applicant_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reimbursement_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_expense_no'), 'expenses', ['expense_no'], unique=True)
    op.create_table('manufacturer_external_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('open_id', sa.String(length=100), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=36), nullable=False),
    sa.Column('brand_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturer_external_identities_open_id'), 'manufacturer_external_identities', ['open_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_no', sa.String(length=50), nullable=False),
    sa.Column('payee', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_no'), 'payments', ['payment_no'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('warehouse_type', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_table('manufacturer_settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('settlement_no', sa.String(length=50), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=36), nullable=True),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('settlement_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('approved_claim_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unsettled_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturer_settlements_settlement_no'), 'manufacturer_settlements', ['settlement_no'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('salesman_id', sa.String(length=36), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('settlement_mode_snapshot', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['salesman_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_table('policy_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_no', sa.String(length=50), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=36), nullable=True),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('claim_batch_period', sa.String(length=20), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('approved_total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unsettled_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['claimed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_claims_claim_no'), 'policy_claims', ['claim_no'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('claim_settlement_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('settlement_id', sa.String(length=36), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['policy_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['manufacturer_settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stock_in_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_purchase_order_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'warehouse_id', 'batch_no')
    )
    op.create_index(op.f('ix_inventory_batch_no'), 'inventory', ['batch_no'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cost_price_snapshot', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_source', sa.String(length=30), nullable=False),
    sa.Column('approval_mode', sa.String(length=30), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('usage_purpose', sa.Text(), nullable=True),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('policy_version_id', sa.String(length=100), nullable=True),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheme_no', sa.String(length=100), nullable=True),
    sa.Column('internal_approved_by', sa.String(length=36), nullable=True),
    sa.Column('manufacturer_approved_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['internal_approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_receipt_no'), 'receipts', ['receipt_no'], unique=True)
    op.create_table('receivables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receivable_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivables_receivable_no'), 'receivables', ['receivable_no'], unique=True)
    op.create_table('stock_flow',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flow_no', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('flow_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('source_order_id', sa.String(length=36), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_flow_batch_no'), 'stock_flow', ['batch_no'], unique=False)
    op.create_index(op.f('ix_stock_flow_flow_no'), 'stock_flow', ['flow_no'], unique=True)
    op.create_table('inspection_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_no', sa.String(length=50), nullable=False),
    sa.Column('case_type', sa.String(length=30), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=True),
    sa.Column('qrcode', sa.String(length=200), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('found_location', sa.String(length=200), nullable=True),
    sa.Column('found_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('found_by', sa.String(length=36), nullable=True),
    sa.Column('original_order_id', sa.String(length=36), nullable=True),
    sa.Column('original_customer_id', sa.String(length=36), nullable=True),
    sa.Column('original_sale_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('recovery_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('manufacturer_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rebate_deduction_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('into_backup_stock', sa.Boolean(), nullable=False),
    sa.Column('backup_stock_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('related_inventory_flow_id', sa.String(length=36), nullable=True),
    sa.Column('related_payment_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['found_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['original_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['original_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['related_inventory_flow_id'], ['stock_flow.id'], ),
    sa.ForeignKeyConstraint(['related_payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_cases_barcode'), 'inspection_cases', ['barcode'], unique=False)
    op.create_index(op.f('ix_inspection_cases_batch_no'), 'inspection_cases', ['batch_no'], unique=False)
    op.create_index(op.f('ix_inspection_cases_case_no'), 'inspection_cases', ['case_no'], unique=True)
    op.create_table('inventory_barcodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=False),
    sa.Column('barcode_type', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('stock_in_id', sa.String(length=36), nullable=True),
    sa.Column('parent_barcode', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outbound_stock_flow_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outbound_stock_flow_id'], ['stock_flow.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stock_in_id'], ['stock_flow.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_barcodes_barcode'), 'inventory_barcodes', ['barcode'], unique=True)
    op.create_index(op.f('ix_inventory_barcodes_batch_no'), 'inventory_barcodes', ['batch_no'], unique=False)
    op.create_index(op.f('ix_inventory_barcodes_parent_barcode'), 'inventory_barcodes', ['parent_barcode'], unique=False)
    op.create_table('market_cleanup_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_no', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=True),
    sa.Column('qrcode', sa.String(length=200), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('found_location', sa.String(length=200), nullable=True),
    sa.Column('found_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('found_by', sa.String(length=36), nullable=True),
    sa.Column('buyback_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_buyback_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('manufacturer_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('into_main_warehouse', sa.Boolean(), nullable=False),
    sa.Column('main_warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('rebate_increase_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('related_inventory_flow_id', sa.String(length=36), nullable=True),
    sa.Column('related_payment_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['found_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['main_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['related_inventory_flow_id'], ['stock_flow.id'], ),
    sa.ForeignKeyConstraint(['related_payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_cleanup_cases_barcode'), 'market_cleanup_cases', ['barcode'], unique=False)
    op.create_index(op.f('ix_market_cleanup_cases_batch_no'), 'market_cleanup_cases', ['batch_no'], unique=False)
    op.create_index(op.f('ix_market_cleanup_cases_case_no'), 'market_cleanup_cases', ['case_no'], unique=True)
    op.create_table('policy_usage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_request_id', sa.String(length=36), nullable=False),
    sa.Column('benefit_item_type', sa.String(length=50), nullable=False),
    sa.Column('usage_scene', sa.String(length=200), nullable=True),
    sa.Column('usage_applicant_id', sa.String(length=36), nullable=True),
    sa.Column('planned_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reimbursement_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('advance_payer_type', sa.String(length=20), nullable=True),
    sa.Column('advance_employee_id', sa.String(length=36), nullable=True),
    sa.Column('advance_customer_id', sa.String(length=36), nullable=True),
    sa.Column('advance_company_account_id', sa.String(length=36), nullable=True),
    sa.Column('execution_status', sa.String(length=20), nullable=False),
    sa.Column('claim_status', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['advance_company_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['advance_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['advance_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['policy_request_id'], ['policy_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_applicant_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_out_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('stock_flow_id', sa.String(length=36), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('allocated_cost_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cost_allocation_mode', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_flow_id'], ['stock_flow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_out_allocations_batch_no'), 'stock_out_allocations', ['batch_no'], unique=False)
    op.create_table('payment_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_no', sa.String(length=50), nullable=False),
    sa.Column('source_usage_record_id', sa.String(length=36), nullable=True),
    sa.Column('related_claim_id', sa.String(length=36), nullable=True),
    sa.Column('payee_type', sa.String(length=20), nullable=True),
    sa.Column('payee_employee_id', sa.String(length=36), nullable=True),
    sa.Column('payee_customer_id', sa.String(length=36), nullable=True),
    sa.Column('payee_other_name', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payable_account_type', sa.String(length=20), nullable=True),
    sa.Column('payable_account_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payable_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['payee_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['payee_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['related_claim_id'], ['policy_claims.id'], ),
    sa.ForeignKeyConstraint(['source_usage_record_id'], ['policy_usage_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_requests_request_no'), 'payment_requests', ['request_no'], unique=True)
    op.create_table('policy_claim_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('source_usage_record_id', sa.String(length=36), nullable=False),
    sa.Column('declared_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('advance_payer_type_snapshot', sa.String(length=20), nullable=True),
    sa.Column('advance_payer_employee_snapshot', sa.String(length=36), nullable=True),
    sa.Column('advance_payer_customer_snapshot', sa.String(length=36), nullable=True),
    sa.Column('advance_payer_company_snapshot', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['advance_payer_company_snapshot'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['advance_payer_customer_snapshot'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['advance_payer_employee_snapshot'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['policy_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_usage_record_id'], ['policy_usage_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_claim_items')
    op.drop_index(op.f('ix_payment_requests_request_no'), table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_index(op.f('ix_stock_out_allocations_batch_no'), table_name='stock_out_allocations')
    op.drop_table('stock_out_allocations')
    op.drop_table('policy_usage_records')
    op.drop_index(op.f('ix_market_cleanup_cases_case_no'), table_name='market_cleanup_cases')
    op.drop_index(op.f('ix_market_cleanup_cases_batch_no'), table_name='market_cleanup_cases')
    op.drop_index(op.f('ix_market_cleanup_cases_barcode'), table_name='market_cleanup_cases')
    op.drop_table('market_cleanup_cases')
    op.drop_index(op.f('ix_inventory_barcodes_parent_barcode'), table_name='inventory_barcodes')
    op.drop_index(op.f('ix_inventory_barcodes_batch_no'), table_name='inventory_barcodes')
    op.drop_index(op.f('ix_inventory_barcodes_barcode'), table_name='inventory_barcodes')
    op.drop_table('inventory_barcodes')
    op.drop_index(op.f('ix_inspection_cases_case_no'), table_name='inspection_cases')
    op.drop_index(op.f('ix_inspection_cases_batch_no'), table_name='inspection_cases')
    op.drop_index(op.f('ix_inspection_cases_barcode'), table_name='inspection_cases')
    op.drop_table('inspection_cases')
    op.drop_index(op.f('ix_stock_flow_flow_no'), table_name='stock_flow')
    op.drop_index(op.f('ix_stock_flow_batch_no'), table_name='stock_flow')
    op.drop_table('stock_flow')
    op.drop_index(op.f('ix_receivables_receivable_no'), table_name='receivables')
    op.drop_table('receivables')
    op.drop_index(op.f('ix_receipts_receipt_no'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_table('policy_requests')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_batch_no'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('claim_settlement_links')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_policy_claims_claim_no'), table_name='policy_claims')
    op.drop_table('policy_claims')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_manufacturer_settlements_settlement_no'), table_name='manufacturer_settlements')
    op.drop_table('manufacturer_settlements')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payments_payment_no'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_manufacturer_external_identities_open_id'), table_name='manufacturer_external_identities')
    op.drop_table('manufacturer_external_identities')
    op.drop_index(op.f('ix_expenses_expense_no'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_brands_code'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_expense_categories_code'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_employees_open_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_no'), table_name='employees')
    op.drop_table('employees')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
